version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-evolution_manager}
      - DATABASE_URL=postgresql://${DB_USERNAME:-postgres}:${DB_PASSWORD:-password}@${DB_HOST:-db}:${DB_PORT:-5432}/${DB_NAME:-reffix_manager}?schema=public
      - EVOLUTION_API_URL=${EVOLUTION_API_URL:-http://localhost:8080}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY:-your-evolution-api-key}
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - evolution-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - evolution-network

  # PostgreSQL - Opcional (apenas se não tiver um externo)
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-evolution_manager}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - evolution-network
    profiles:
      - local-db  # Só roda se especificar --profile local-db

volumes:
  postgres_data:

networks:
  evolution-network:
    driver: bridge
